version: "3.7"
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    networks:
      - db-network
    environment:
      PORT: 3000
      CLIENT_URL: http://localhost:3001
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASE: demo
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "test", "-U", "root"]
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo
    ports:
      - "5432:5432" # Testing purposes
    networks:
      - db-network

networks:
  db-network:
