version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/heartbeat"]
    environment:
      PORT: 3001
      CLIENT_URL: http://localhost:3000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASE: demo
    ports:
      - "3001:3001"
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "test", "-U", "root"]
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo
    ports:
      - "5432:5432" # Testing purposes
    networks:
      - db-network
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
      - db

networks:
  db-network:
