version: "3.7"
services:
  db-test:
    image: node:20.9.0
    command: ["npx", "jest", "--logHeapUsage", "test/infrastructure"]
    volumes:
      - .:/app
      - ../node_modules:/node_modules:ro
    working_dir: /app
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=test
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CLIENT_URL=http://localhost:3000
      - PORT=3000
    depends_on:
      - db
    networks:
      - db-network

  db:
    build:
      context: ..
      dockerfile: db.Dockerfile
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "test", "-U", "root"]
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    networks:
      - db-network

networks:
  db-network:
