on:
  pull_request:
    paths:
      - "api/**"
      - "package.json"
      - "yarn.lock"
  push:
    branches:
      - master
jobs:
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - name: "Install dependencies"
        run: "yarn --cwd api install --frozen-lockfile"
      - name: "Run linter"
        run: "yarn workspace api run lint"
