on:
  push:
    paths:
      - "frontend/**"
    branches:
      - master
    tags:
      - "v*.*.*"
jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: "yarn"
          cache-dependency-path: "frontend/yarn.lock"
      - name: "Install dependencies"
        run: "yarn --cwd frontend install --frozen-lockfile"
      - name: "Run linter"
        run: "yarn workspace frontend run lint"
