on:
  push:
    paths:
      - "api/**"
    branches:
      - master
    tags:
      - "v*.*.*"
jobs:
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: "yarn"
          cache-dependency-path: "api/yarn.lock"
      - name: "Install dependencies"
        run: "yarn --cwd api install --frozen-lockfile"
      - name: "Run linter"
        run: "yarn workspace api run lint"
