on: [push]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: "Run unit tests"
        run: "yarn workspace api run test:nodb"

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: "Run unit tests"
        run: "yarn workspace api run test:db"
